import { createFileRoute } from "@tanstack/react-router";
import {
  getClientIp,
  getUserAgent,
  jsonResponse,
  recordAudit,
  checkRateLimits,
  type RateLimitRule,
} from "@/lib/security.server";

/**
 * Passwordless Email-OTP REQUEST endpoint.
 *
 * The code is generated by Supabase (`admin.generateLink`, which returns the
 * one-time code WITHOUT sending anything) and delivered by us through the app's
 * own Resend pipeline — not Supabase's built-in email, whose test-only sender
 * rate-limits and silently drops login codes. The client still verifies the code
 * against Supabase Auth with `verifyOtp({ type: "email" })`.
 *
 * It runs server-side (rather than from the browser) to apply per-IP and
 * per-email limits with the same Postgres-backed limiter the contact and enquiry
 * endpoints use, and because generating the code requires the service-role key.
 *
 * THREE INVARIANTS, each with a security reason:
 *
 *  1. ENUMERATION-SAFE. The response is identical whether or not the email is
 *     registered — always `{ ok: true }` on a well-formed request. A first-time
 *     email is provisioned (a pre-confirmed passwordless account) rather than
 *     rejected, so "exists vs not" never changes the outcome.
 *
 *  2. THE OTP VALUE IS NEVER LOGGED OR RETURNED. The code is generated here so it
 *     can be emailed, but it travels only in the message body handed to the email
 *     provider. It is never logged, never returned to the client, and never
 *     audited — audit rows record only a `delivered` boolean, the event, IP, and
 *     a redacted email.
 *
 *  3. THE REDIRECT IS VALIDATED. `next` is constrained to an internal absolute
 *     path here, mirroring safeRedirect in routes/auth.tsx.
 */

const PER_IP_OTP: RateLimitRule = {
  name: "otp:ip:hourly",
  windowSeconds: 3600,
  max: 8, // a human needs one or two codes; eight per hour per IP is generous
};
const PER_EMAIL_OTP: RateLimitRule = {
  name: "otp:email:hourly",
  windowSeconds: 3600,
  max: 5, // caps targeting a single inbox regardless of source IP
};

/** Trim + lowercase. A single canonical form so "A@x.com " and "a@x.com" collide. */
export function normalizeEmail(raw: unknown): string {
  return typeof raw === "string" ? raw.trim().toLowerCase() : "";
}

/** RFC-pragmatic email shape. Not exhaustive — just enough to reject junk early. */
const EMAIL_RE = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;

/** Redact for audit: keep first char + domain, drop the rest of the local part. */
function redactEmail(email: string): string {
  const [local, domain] = email.split("@");
  if (!domain) return "invalid";
  return `${local.slice(0, 1)}***@${domain}`;
}

/**
 * Internal-path guard, identical rule to routes/auth.tsx safeRedirect: must be a
 * root-relative path, never protocol-relative (`//host`), never back into /auth.
 */
function safeNext(next: unknown): string {
  if (typeof next !== "string") return "/";
  if (!next.startsWith("/") || next.startsWith("//")) return "/";
  if (next.startsWith("/auth")) return "/";
  return next;
}

async function countRecentOtp(
  field: "ip_address" | "subject_id",
  value: string,
  sinceIso: string,
): Promise<number> {
  const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
  const { count } = await supabaseAdmin
    .from("audit_logs")
    .select("*", { count: "exact", head: true })
    .eq("event", "auth.otp.requested")
    .eq(field, value)
    .gte("created_at", sinceIso);
  return count ?? 0;
}

export const Route = createFileRoute("/api/auth/request-otp")({
  server: {
    handlers: {
      POST: async ({ request }) => {
        const ip = getClientIp(request);
        const userAgent = getUserAgent(request);

        let body: { email?: unknown; next?: unknown } = {};
        try {
          body = (await request.json()) as typeof body;
        } catch {
          return jsonResponse({ error: "Invalid request body." }, 400);
        }

        const email = normalizeEmail(body.email);
        const next = safeNext(body.next);

        // Malformed email is rejected BEFORE any limiter or Supabase call, so junk
        // never consumes a rate-limit slot. This is a format check, not an
        // existence check — it reveals nothing about who is registered.
        if (!EMAIL_RE.test(email) || email.length > 254) {
          return jsonResponse({ error: "Enter a valid email address." }, 400);
        }

        // Per-IP then per-email. `subject_id` carries the redacted email so the
        // limiter counts a single inbox without storing the raw address as an id.
        const redacted = redactEmail(email);
        const limit = await checkRateLimits([
          { rule: PER_IP_OTP, count: (since) => countRecentOtp("ip_address", ip, since) },
          {
            rule: PER_EMAIL_OTP,
            count: (since) => countRecentOtp("subject_id", redacted, since),
          },
        ]);
        if (!limit.allowed) {
          await recordAudit({
            event: "auth.otp.rejected",
            outcome: "rate_limited",
            ip,
            userAgent,
            subjectId: redacted,
            details: { rule: limit.rule?.name },
          });
          // Generic message; does not distinguish which limit or whether the email exists.
          return jsonResponse({ error: "Too many code requests. Please wait and try again." }, 429);
        }

        const { APP_URL } = await import("@/config/app");
        const { supabaseAdmin } = await import("@/integrations/supabase/client.server");

        // We generate the code but deliver it OURSELVES via Resend, rather than
        // letting Supabase send it. Supabase's built-in email is test-only (a very
        // low hourly cap and poor deliverability), which was silently dropping
        // login codes. `admin.generateLink` returns the one-time code WITHOUT
        // sending any email; we then send it through the app's branded transactional
        // email. The client still verifies it with `verifyOtp({ type: "email" })`.
        const redirectTo = `${APP_URL}/auth/callback?next=${encodeURIComponent(next)}`;
        let gen = await supabaseAdmin.auth.admin.generateLink({
          type: "magiclink",
          email,
          options: { redirectTo },
        });
        // `magiclink` requires an existing user; create a pre-confirmed passwordless
        // account if this is a first-time email (mirrors the old shouldCreateUser).
        if (gen.error && /user|not found|exist|registered/i.test(gen.error.message ?? "")) {
          await supabaseAdmin.auth.admin.createUser({ email, email_confirm: true }).catch(() => {});
          gen = await supabaseAdmin.auth.admin.generateLink({
            type: "magiclink",
            email,
            options: { redirectTo },
          });
        }

        // Deliver the code via Resend. The OTP travels only in the email body sent
        // to the provider — it is never logged, audited, or returned to the client.
        let delivered = false;
        const otp = gen.data?.properties?.email_otp;
        if (!gen.error && otp) {
          const { otpEmail } = await import("@/shared/services/email/templates");
          const { sendTransactionalEmail } = await import("@/shared/services/emailService");
          const userName = (gen.data?.user?.user_metadata?.full_name as string | undefined) ?? null;
          const rendered = otpEmail({ userName, otp, expiry: "10 minutes" });
          const result = await sendTransactionalEmail({
            to: email,
            subject: rendered.subject,
            eventType: "security_event",
            recipientName: userName ?? undefined,
            htmlBody: rendered.htmlBody,
            textBody: rendered.textBody,
            // Identifiers only — never the code itself.
            metadata: { flow: "email_otp_login" },
          });
          delivered = result.status === "sent";
        }

        // Record the attempt for rate-limiting REGARDLESS of outcome, so a delivery
        // error cannot be used to bypass the limiter by retrying.
        await recordAudit({
          event: "auth.otp.requested",
          outcome: delivered ? "success" : "error",
          ip,
          userAgent,
          subjectId: redacted,
          // No token, no raw email. Only whether we delivered the code.
          details: { delivered },
        });

        // ENUMERATION-SAFE: the same 200 whether the address exists, was just
        // created, or the provider hiccuped. The user is told to check their inbox
        // either way; a real failure surfaces as "no code arrived", not as a
        // response that reveals account existence.
        return jsonResponse({ ok: true, next }, 200);
      },
    },
  },
});
