/**
 * Runtime detection of the `properties` video/location columns.
 *
 * Migration `20260815131921_add_video_and_location_to_properties.sql` adds the
 * video tour and location-context columns. Until it is applied, naming any of
 * them makes PostgREST reject the *entire* query with a 400 — one missing
 * column silently collapsed every listing, search, detail and owner-dashboard
 * query onto fallback data or an error page.
 *
 * Rather than delete the feature, each query optimistically asks for the full
 * schema; the first `42703` latches the capability off and the query is retried
 * against the columns that do exist. When the migration lands, the first query
 * succeeds and the richer data flows again with no code change.
 *
 * The flag is per module instance (per browser tab, per server worker), so a
 * newly-migrated database is picked up by every fresh instance without a deploy.
 *
 * KNOWN LIMITATION — the flag is all-or-nothing.
 * A 42703 on ANY extended column disables EVERY extended column, because one
 * retry cannot tell which of them the database was objecting to. This is not
 * hypothetical: production had all six location columns and both original video
 * columns, but was missing the three video-metadata columns above. That single
 * absence switched off `locality` too, so every SEO slug generated by
 * `generatePropertySlug` silently omitted the locality segment.
 *
 * Splitting this into independent location/video capabilities needs a two-step
 * retry ladder (both -> location-only -> base) through the busiest query path in
 * the app, so it is deliberately NOT done here. Keep the two column groups in
 * one migration, and grant them together, and the coupling stays harmless.
 */

/** Columns added by migration 20260815131921. */
export const PROPERTY_LOCATION_COLUMNS = [
  "locality",
  "landmark",
  "metro_station",
  "it_park",
  "college",
  "hospital",
] as const;

/**
 * Video columns from 20260815131921 plus the three metadata columns that were
 * stranded in `supabase/migrations/properties/20260815190000` — a subdirectory
 * the Supabase CLI never reads — and are recovered by 20260818140100.
 */
export const PROPERTY_VIDEO_COLUMNS = [
  "video_url",
  "video_status",
  "video_thumbnail_url",
  "video_duration",
  "video_uploaded_at",
] as const;

/** PostgreSQL `undefined_column`. */
const UNDEFINED_COLUMN = "42703";
/** PostgreSQL `insufficient_privilege`. */
const INSUFFICIENT_PRIVILEGE = "42501";

/**
 * True when the extended select failed for a reason a base-column retry can fix.
 *
 * Missing (42703) is the obvious case. Ungranted (42501) matters just as much
 * here, because `public.properties` uses COLUMN-LEVEL grants: a column can exist
 * and still be unreadable, and asking for one rejects the whole select exactly
 * as a missing column does.
 *
 * That was not hypothetical. 20260817140000_add_critical_property_specs.sql
 * added nine columns without granting them, and they sat unreadable behind an
 * earlier 42703 on `pincode`. Handling only 42703 meant that fixing `pincode` —
 * the obvious repair — would have moved the failure to 42501, which nothing
 * caught, and taken down every public property query.
 *
 * Retrying is safe even when the cause is not column-level: the retry requests
 * the base columns, and if that fails too the real error propagates untouched.
 */
export function isExtendedColumnUnavailable(error: { code?: string } | null | undefined): boolean {
  return error?.code === UNDEFINED_COLUMN || error?.code === INSUFFICIENT_PRIVILEGE;
}

export interface SchemaCapability {
  /** False once a query has proven the extended columns are absent. */
  shouldTry(): boolean;
  /** Latches the capability on or off after a query result. */
  record(available: boolean): void;
  /** true / false once known, null while untested. */
  state(): boolean | null;
  /** Test seam — forces the next query to probe again. */
  reset(): void;
}

export function createSchemaCapability(label: string): SchemaCapability {
  let available: boolean | null = null;
  let warned = false;

  return {
    shouldTry: () => available !== false,
    record(next: boolean) {
      if (!next && !warned) {
        warned = true;
        console.warn(
          `[${label}] extended property columns absent — serving the base schema. ` +
            `Check which of these the database actually has before blaming a migration: ` +
            `${[...PROPERTY_LOCATION_COLUMNS, ...PROPERTY_VIDEO_COLUMNS].join(", ")}`,
        );
      }
      available = next;
    },
    state: () => available,
    reset() {
      available = null;
      warned = false;
    },
  };
}

/**
 * Removes keys the database does not have yet, so a write cannot fail on a
 * column that a read has already proven missing.
 */
export function stripExtendedColumns<T extends object>(
  input: T,
  extendedAvailable: boolean | null,
): T {
  if (extendedAvailable !== false) return input;
  const blocked = new Set<string>([...PROPERTY_LOCATION_COLUMNS, ...PROPERTY_VIDEO_COLUMNS]);
  const out: Record<string, unknown> = {};
  for (const [key, value] of Object.entries(input)) {
    if (!blocked.has(key)) out[key] = value;
  }
  return out as T;
}
