/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SplatRouteImport } from './routes/$'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as ApiPublicEnquiriesRouteImport } from './routes/api/public/enquiries'
import { Route as ApiPublicPropertiesIdContactRouteImport } from './routes/api/public/properties.$id.contact'
import { Route as ApiPublicPropertiesIdReportRouteImport } from './routes/api/public/properties.$id.report'
import { Route as ApiPublicPropertiesIdSaveRouteImport } from './routes/api/public/properties.$id.save'
import { Route as ApiPublicPropertiesIdScheduleVisitRouteImport } from './routes/api/public/properties.$id.schedule-visit'
import { Route as ApiPublicPropertiesIdShareRouteImport } from './routes/api/public/properties.$id.share'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const ApiPublicEnquiriesRoute = ApiPublicEnquiriesRouteImport.update({
  id: '/api/public/enquiries',
  path: '/api/public/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropertiesIdContactRoute =
  ApiPublicPropertiesIdContactRouteImport.update({
    id: '/api/public/properties/$id/contact',
    path: '/api/public/properties/$id/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPropertiesIdReportRoute =
  ApiPublicPropertiesIdReportRouteImport.update({
    id: '/api/public/properties/$id/report',
    path: '/api/public/properties/$id/report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPropertiesIdSaveRoute =
  ApiPublicPropertiesIdSaveRouteImport.update({
    id: '/api/public/properties/$id/save',
    path: '/api/public/properties/$id/save',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPropertiesIdScheduleVisitRoute =
  ApiPublicPropertiesIdScheduleVisitRouteImport.update({
    id: '/api/public/properties/$id/schedule-visit',
    path: '/api/public/properties/$id/schedule-visit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPropertiesIdShareRoute =
  ApiPublicPropertiesIdShareRouteImport.update({
    id: '/api/public/properties/$id/share',
    path: '/api/public/properties/$id/share',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/public/enquiries': typeof ApiPublicEnquiriesRoute
  '/api/public/properties/$id/contact': typeof ApiPublicPropertiesIdContactRoute
  '/api/public/properties/$id/report': typeof ApiPublicPropertiesIdReportRoute
  '/api/public/properties/$id/save': typeof ApiPublicPropertiesIdSaveRoute
  '/api/public/properties/$id/schedule-visit': typeof ApiPublicPropertiesIdScheduleVisitRoute
  '/api/public/properties/$id/share': typeof ApiPublicPropertiesIdShareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties': typeof PropertiesIndexRoute
  '/api/public/enquiries': typeof ApiPublicEnquiriesRoute
  '/api/public/properties/$id/contact': typeof ApiPublicPropertiesIdContactRoute
  '/api/public/properties/$id/report': typeof ApiPublicPropertiesIdReportRoute
  '/api/public/properties/$id/save': typeof ApiPublicPropertiesIdSaveRoute
  '/api/public/properties/$id/schedule-visit': typeof ApiPublicPropertiesIdScheduleVisitRoute
  '/api/public/properties/$id/share': typeof ApiPublicPropertiesIdShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$': typeof SplatRoute
  '/auth': typeof AuthRoute
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
  '/api/public/enquiries': typeof ApiPublicEnquiriesRoute
  '/api/public/properties/$id/contact': typeof ApiPublicPropertiesIdContactRoute
  '/api/public/properties/$id/report': typeof ApiPublicPropertiesIdReportRoute
  '/api/public/properties/$id/save': typeof ApiPublicPropertiesIdSaveRoute
  '/api/public/properties/$id/schedule-visit': typeof ApiPublicPropertiesIdScheduleVisitRoute
  '/api/public/properties/$id/share': typeof ApiPublicPropertiesIdShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/auth'
    | '/favorites'
    | '/properties'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/properties/$id'
    | '/properties/'
    | '/api/public/enquiries'
    | '/api/public/properties/$id/contact'
    | '/api/public/properties/$id/report'
    | '/api/public/properties/$id/save'
    | '/api/public/properties/$id/schedule-visit'
    | '/api/public/properties/$id/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/auth'
    | '/favorites'
    | '/sitemap.xml'
    | '/admin'
    | '/dashboard'
    | '/properties/$id'
    | '/properties'
    | '/api/public/enquiries'
    | '/api/public/properties/$id/contact'
    | '/api/public/properties/$id/report'
    | '/api/public/properties/$id/save'
    | '/api/public/properties/$id/schedule-visit'
    | '/api/public/properties/$id/share'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$'
    | '/auth'
    | '/favorites'
    | '/properties'
    | '/sitemap.xml'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/properties/$id'
    | '/properties/'
    | '/api/public/enquiries'
    | '/api/public/properties/$id/contact'
    | '/api/public/properties/$id/report'
    | '/api/public/properties/$id/save'
    | '/api/public/properties/$id/schedule-visit'
    | '/api/public/properties/$id/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SplatRoute: typeof SplatRoute
  AuthRoute: typeof AuthRoute
  FavoritesRoute: typeof FavoritesRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicEnquiriesRoute: typeof ApiPublicEnquiriesRoute
  ApiPublicPropertiesIdContactRoute: typeof ApiPublicPropertiesIdContactRoute
  ApiPublicPropertiesIdReportRoute: typeof ApiPublicPropertiesIdReportRoute
  ApiPublicPropertiesIdSaveRoute: typeof ApiPublicPropertiesIdSaveRoute
  ApiPublicPropertiesIdScheduleVisitRoute: typeof ApiPublicPropertiesIdScheduleVisitRoute
  ApiPublicPropertiesIdShareRoute: typeof ApiPublicPropertiesIdShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/api/public/enquiries': {
      id: '/api/public/enquiries'
      path: '/api/public/enquiries'
      fullPath: '/api/public/enquiries'
      preLoaderRoute: typeof ApiPublicEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/contact': {
      id: '/api/public/properties/$id/contact'
      path: '/api/public/properties/$id/contact'
      fullPath: '/api/public/properties/$id/contact'
      preLoaderRoute: typeof ApiPublicPropertiesIdContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/report': {
      id: '/api/public/properties/$id/report'
      path: '/api/public/properties/$id/report'
      fullPath: '/api/public/properties/$id/report'
      preLoaderRoute: typeof ApiPublicPropertiesIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/save': {
      id: '/api/public/properties/$id/save'
      path: '/api/public/properties/$id/save'
      fullPath: '/api/public/properties/$id/save'
      preLoaderRoute: typeof ApiPublicPropertiesIdSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/schedule-visit': {
      id: '/api/public/properties/$id/schedule-visit'
      path: '/api/public/properties/$id/schedule-visit'
      fullPath: '/api/public/properties/$id/schedule-visit'
      preLoaderRoute: typeof ApiPublicPropertiesIdScheduleVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/share': {
      id: '/api/public/properties/$id/share'
      path: '/api/public/properties/$id/share'
      fullPath: '/api/public/properties/$id/share'
      preLoaderRoute: typeof ApiPublicPropertiesIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SplatRoute: SplatRoute,
  AuthRoute: AuthRoute,
  FavoritesRoute: FavoritesRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicEnquiriesRoute: ApiPublicEnquiriesRoute,
  ApiPublicPropertiesIdContactRoute: ApiPublicPropertiesIdContactRoute,
  ApiPublicPropertiesIdReportRoute: ApiPublicPropertiesIdReportRoute,
  ApiPublicPropertiesIdSaveRoute: ApiPublicPropertiesIdSaveRoute,
  ApiPublicPropertiesIdScheduleVisitRoute:
    ApiPublicPropertiesIdScheduleVisitRoute,
  ApiPublicPropertiesIdShareRoute: ApiPublicPropertiesIdShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
