/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'

const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/properties': typeof PropertiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/favorites': typeof FavoritesRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/properties/$id': typeof PropertiesIdRoute
  '/properties/': typeof PropertiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/favorites'
    | '/properties'
    | '/properties/$id'
    | '/properties/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/favorites' | '/properties/$id' | '/properties'
  id:
    | '__root__'
    | '/'
    | '/favorites'
    | '/properties'
    | '/properties/$id'
    | '/properties/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FavoritesRoute: typeof FavoritesRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
  }
}

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FavoritesRoute: FavoritesRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
