/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiePolicyRouteImport } from './routes/cookie-policy'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PlansRouteImport } from './routes/plans'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as RefundPolicyRouteImport } from './routes/refund-policy'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsOfServiceRouteImport } from './routes/terms-of-service'
import { Route as WhyUsRouteImport } from './routes/why-us'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthCallbackRouteImport } from './routes/auth_.callback'
import { Route as BuyIndexRouteImport } from './routes/buy.index'
import { Route as CommercialIndexRouteImport } from './routes/commercial.index'
import { Route as ListPropertyIndexRouteImport } from './routes/list-property.index'
import { Route as ListPropertyWizardRouteImport } from './routes/list-property.wizard'
import { Route as PropertiesIndexRouteImport } from './routes/properties.index'
import { Route as PropertiesIdRouteImport } from './routes/properties.$id'
import { Route as RentIndexRouteImport } from './routes/rent.index'
import { Route as TenantMatchesRouteImport } from './routes/tenant.matches'
import { Route as TenantOnboardingRouteImport } from './routes/tenant.onboarding'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAccessRouteImport } from './routes/_authenticated/admin/access'
import { Route as AuthenticatedAdminActivityRouteImport } from './routes/_authenticated/admin/activity'
import { Route as AuthenticatedAdminAnalyticsRouteImport } from './routes/_authenticated/admin/analytics'
import { Route as AuthenticatedAdminModerationRouteImport } from './routes/_authenticated/admin/moderation'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AuthenticatedDashboardAgentRouteImport } from './routes/_authenticated/dashboard/agent'
import { Route as AuthenticatedDashboardCustomerRouteImport } from './routes/_authenticated/dashboard/customer'
import { Route as AuthenticatedDashboardOwnerRouteImport } from './routes/_authenticated/dashboard/owner'
import { Route as AuthenticatedDashboardTenantProfileRouteImport } from './routes/_authenticated/dashboard/tenant-profile'
import { Route as ApiAuthLoginNotificationRouteImport } from './routes/api/auth/login-notification'
import { Route as ApiPublicEnquiriesRouteImport } from './routes/api/public/enquiries'
import { Route as BuyCityIndexRouteImport } from './routes/buy.$city.index'
import { Route as BuyCityLocalityRouteImport } from './routes/buy.$city.$locality'
import { Route as CommercialCityIndexRouteImport } from './routes/commercial.$city.index'
import { Route as CommercialCityLocalityRouteImport } from './routes/commercial.$city.$locality'
import { Route as RentCityIndexRouteImport } from './routes/rent.$city.index'
import { Route as RentCityLocalityRouteImport } from './routes/rent.$city.$locality'
import { Route as ApiPublicPropertiesIdContactRouteImport } from './routes/api/public/properties.$id.contact'
import { Route as ApiPublicPropertiesIdReportRouteImport } from './routes/api/public/properties.$id.report'
import { Route as ApiPublicPropertiesIdSaveRouteImport } from './routes/api/public/properties.$id.save'
import { Route as ApiPublicPropertiesIdScheduleVisitRouteImport } from './routes/api/public/properties.$id.schedule-visit'
import { Route as ApiPublicPropertiesIdShareRouteImport } from './routes/api/public/properties.$id.share'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiePolicyRoute = CookiePolicyRouteImport.update({
  id: '/cookie-policy',
  path: '/cookie-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PlansRoute = PlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundPolicyRoute = RefundPolicyRouteImport.update({
  id: '/refund-policy',
  path: '/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsOfServiceRoute = TermsOfServiceRouteImport.update({
  id: '/terms-of-service',
  path: '/terms-of-service',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyUsRoute = WhyUsRouteImport.update({
  id: '/why-us',
  path: '/why-us',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth_/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyIndexRoute = BuyIndexRouteImport.update({
  id: '/buy/',
  path: '/buy/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialIndexRoute = CommercialIndexRouteImport.update({
  id: '/commercial/',
  path: '/commercial/',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyIndexRoute = ListPropertyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ListPropertyRoute,
} as any)
const ListPropertyWizardRoute = ListPropertyWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => ListPropertyRoute,
} as any)
const PropertiesIndexRoute = PropertiesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PropertiesRoute,
} as any)
const PropertiesIdRoute = PropertiesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PropertiesRoute,
} as any)
const RentIndexRoute = RentIndexRouteImport.update({
  id: '/rent/',
  path: '/rent/',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantMatchesRoute = TenantMatchesRouteImport.update({
  id: '/tenant/matches',
  path: '/tenant/matches',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantOnboardingRoute = TenantOnboardingRouteImport.update({
  id: '/tenant/onboarding',
  path: '/tenant/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedAdminAccessRoute =
  AuthenticatedAdminAccessRouteImport.update({
    id: '/access',
    path: '/access',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminActivityRoute =
  AuthenticatedAdminActivityRouteImport.update({
    id: '/activity',
    path: '/activity',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAnalyticsRoute =
  AuthenticatedAdminAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminModerationRoute =
  AuthenticatedAdminModerationRouteImport.update({
    id: '/moderation',
    path: '/moderation',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRouteRoute,
} as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAgentRoute =
  AuthenticatedDashboardAgentRouteImport.update({
    id: '/agent',
    path: '/agent',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardCustomerRoute =
  AuthenticatedDashboardCustomerRouteImport.update({
    id: '/customer',
    path: '/customer',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardOwnerRoute =
  AuthenticatedDashboardOwnerRouteImport.update({
    id: '/owner',
    path: '/owner',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardTenantProfileRoute =
  AuthenticatedDashboardTenantProfileRouteImport.update({
    id: '/tenant-profile',
    path: '/tenant-profile',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const ApiAuthLoginNotificationRoute =
  ApiAuthLoginNotificationRouteImport.update({
    id: '/api/auth/login-notification',
    path: '/api/auth/login-notification',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicEnquiriesRoute = ApiPublicEnquiriesRouteImport.update({
  id: '/api/public/enquiries',
  path: '/api/public/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyCityIndexRoute = BuyCityIndexRouteImport.update({
  id: '/buy/$city/',
  path: '/buy/$city/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuyCityLocalityRoute = BuyCityLocalityRouteImport.update({
  id: '/buy/$city/$locality',
  path: '/buy/$city/$locality',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialCityIndexRoute = CommercialCityIndexRouteImport.update({
  id: '/commercial/$city/',
  path: '/commercial/$city/',
  getParentRoute: () => rootRouteImport,
} as any)
const CommercialCityLocalityRoute = CommercialCityLocalityRouteImport.update({
  id: '/commercial/$city/$locality',
  path: '/commercial/$city/$locality',
  getParentRoute: () => rootRouteImport,
} as any)
const RentCityIndexRoute = RentCityIndexRouteImport.update({
  id: '/rent/$city/',
  path: '/rent/$city/',
  getParentRoute: () => rootRouteImport,
} as any)
const RentCityLocalityRoute = RentCityLocalityRouteImport.update({
  id: '/rent/$city/$locality',
  path: '/rent/$city/$locality',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPropertiesIdContactRoute =
  ApiPublicPropertiesIdContactRouteImport.update({
    id: '/api/public/properties/$id/contact',
    path: '/api/public/properties/$id/contact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPropertiesIdReportRoute =
  ApiPublicPropertiesIdReportRouteImport.update({
    id: '/api/public/properties/$id/report',
    path: '/api/public/properties/$id/report',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPropertiesIdSaveRoute =
  ApiPublicPropertiesIdSaveRouteImport.update({
    id: '/api/public/properties/$id/save',
    path: '/api/public/properties/$id/save',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPropertiesIdScheduleVisitRoute =
  ApiPublicPropertiesIdScheduleVisitRouteImport.update({
    id: '/api/public/properties/$id/schedule-visit',
    path: '/api/public/properties/$id/schedule-visit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPropertiesIdShareRoute =
  ApiPublicPropertiesIdShareRouteImport.update({
    id: '/api/public/properties/$id/share',
    path: '/api/public/properties/$id/share',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/list-property': typeof ListPropertyRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/why-us': typeof WhyUsRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/list-property/wizard': typeof ListPropertyWizardRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/tenant/matches': typeof TenantMatchesRoute
  '/tenant/onboarding': typeof TenantOnboardingRoute
  '/buy/': typeof BuyIndexRoute
  '/commercial/': typeof CommercialIndexRoute
  '/list-property/': typeof ListPropertyIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/rent/': typeof RentIndexRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/agent': typeof AuthenticatedDashboardAgentRoute
  '/dashboard/customer': typeof AuthenticatedDashboardCustomerRoute
  '/dashboard/owner': typeof AuthenticatedDashboardOwnerRoute
  '/dashboard/tenant-profile': typeof AuthenticatedDashboardTenantProfileRoute
  '/api/auth/login-notification': typeof ApiAuthLoginNotificationRoute
  '/api/public/enquiries': typeof ApiPublicEnquiriesRoute
  '/buy/$city/$locality': typeof BuyCityLocalityRoute
  '/commercial/$city/$locality': typeof CommercialCityLocalityRoute
  '/rent/$city/$locality': typeof RentCityLocalityRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/buy/$city/': typeof BuyCityIndexRoute
  '/commercial/$city/': typeof CommercialCityIndexRoute
  '/rent/$city/': typeof RentCityIndexRoute
  '/api/public/properties/$id/contact': typeof ApiPublicPropertiesIdContactRoute
  '/api/public/properties/$id/report': typeof ApiPublicPropertiesIdReportRoute
  '/api/public/properties/$id/save': typeof ApiPublicPropertiesIdSaveRoute
  '/api/public/properties/$id/schedule-visit': typeof ApiPublicPropertiesIdScheduleVisitRoute
  '/api/public/properties/$id/share': typeof ApiPublicPropertiesIdShareRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/why-us': typeof WhyUsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/list-property/wizard': typeof ListPropertyWizardRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/tenant/matches': typeof TenantMatchesRoute
  '/tenant/onboarding': typeof TenantOnboardingRoute
  '/buy': typeof BuyIndexRoute
  '/commercial': typeof CommercialIndexRoute
  '/list-property': typeof ListPropertyIndexRoute
  '/properties': typeof PropertiesIndexRoute
  '/rent': typeof RentIndexRoute
  '/admin/access': typeof AuthenticatedAdminAccessRoute
  '/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/dashboard/agent': typeof AuthenticatedDashboardAgentRoute
  '/dashboard/customer': typeof AuthenticatedDashboardCustomerRoute
  '/dashboard/owner': typeof AuthenticatedDashboardOwnerRoute
  '/dashboard/tenant-profile': typeof AuthenticatedDashboardTenantProfileRoute
  '/api/auth/login-notification': typeof ApiAuthLoginNotificationRoute
  '/api/public/enquiries': typeof ApiPublicEnquiriesRoute
  '/buy/$city/$locality': typeof BuyCityLocalityRoute
  '/commercial/$city/$locality': typeof CommercialCityLocalityRoute
  '/rent/$city/$locality': typeof RentCityLocalityRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/buy/$city': typeof BuyCityIndexRoute
  '/commercial/$city': typeof CommercialCityIndexRoute
  '/rent/$city': typeof RentCityIndexRoute
  '/api/public/properties/$id/contact': typeof ApiPublicPropertiesIdContactRoute
  '/api/public/properties/$id/report': typeof ApiPublicPropertiesIdReportRoute
  '/api/public/properties/$id/save': typeof ApiPublicPropertiesIdSaveRoute
  '/api/public/properties/$id/schedule-visit': typeof ApiPublicPropertiesIdScheduleVisitRoute
  '/api/public/properties/$id/share': typeof ApiPublicPropertiesIdShareRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/agents': typeof AgentsRoute
  '/auth': typeof AuthRoute
  '/blog': typeof BlogRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookie-policy': typeof CookiePolicyRoute
  '/favorites': typeof FavoritesRoute
  '/help': typeof HelpRoute
  '/list-property': typeof ListPropertyRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/plans': typeof PlansRoute
  '/pricing': typeof PricingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/profile': typeof ProfileRoute
  '/properties': typeof PropertiesRouteWithChildren
  '/refund-policy': typeof RefundPolicyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms-of-service': typeof TermsOfServiceRoute
  '/why-us': typeof WhyUsRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/auth_/callback': typeof AuthCallbackRoute
  '/list-property/wizard': typeof ListPropertyWizardRoute
  '/properties/$id': typeof PropertiesIdRoute
  '/tenant/matches': typeof TenantMatchesRoute
  '/tenant/onboarding': typeof TenantOnboardingRoute
  '/buy/': typeof BuyIndexRoute
  '/commercial/': typeof CommercialIndexRoute
  '/list-property/': typeof ListPropertyIndexRoute
  '/properties/': typeof PropertiesIndexRoute
  '/rent/': typeof RentIndexRoute
  '/_authenticated/admin/access': typeof AuthenticatedAdminAccessRoute
  '/_authenticated/admin/activity': typeof AuthenticatedAdminActivityRoute
  '/_authenticated/admin/analytics': typeof AuthenticatedAdminAnalyticsRoute
  '/_authenticated/admin/moderation': typeof AuthenticatedAdminModerationRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRoute
  '/_authenticated/dashboard/agent': typeof AuthenticatedDashboardAgentRoute
  '/_authenticated/dashboard/customer': typeof AuthenticatedDashboardCustomerRoute
  '/_authenticated/dashboard/owner': typeof AuthenticatedDashboardOwnerRoute
  '/_authenticated/dashboard/tenant-profile': typeof AuthenticatedDashboardTenantProfileRoute
  '/api/auth/login-notification': typeof ApiAuthLoginNotificationRoute
  '/api/public/enquiries': typeof ApiPublicEnquiriesRoute
  '/buy/$city/$locality': typeof BuyCityLocalityRoute
  '/commercial/$city/$locality': typeof CommercialCityLocalityRoute
  '/rent/$city/$locality': typeof RentCityLocalityRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/buy/$city/': typeof BuyCityIndexRoute
  '/commercial/$city/': typeof CommercialCityIndexRoute
  '/rent/$city/': typeof RentCityIndexRoute
  '/api/public/properties/$id/contact': typeof ApiPublicPropertiesIdContactRoute
  '/api/public/properties/$id/report': typeof ApiPublicPropertiesIdReportRoute
  '/api/public/properties/$id/save': typeof ApiPublicPropertiesIdSaveRoute
  '/api/public/properties/$id/schedule-visit': typeof ApiPublicPropertiesIdScheduleVisitRoute
  '/api/public/properties/$id/share': typeof ApiPublicPropertiesIdShareRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/favorites'
    | '/help'
    | '/list-property'
    | '/notifications'
    | '/plans'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/properties'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/why-us'
    | '/admin'
    | '/dashboard'
    | '/auth/callback'
    | '/list-property/wizard'
    | '/properties/$id'
    | '/tenant/matches'
    | '/tenant/onboarding'
    | '/buy/'
    | '/commercial/'
    | '/list-property/'
    | '/properties/'
    | '/rent/'
    | '/admin/access'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/moderation'
    | '/admin/users'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/customer'
    | '/dashboard/owner'
    | '/dashboard/tenant-profile'
    | '/api/auth/login-notification'
    | '/api/public/enquiries'
    | '/buy/$city/$locality'
    | '/commercial/$city/$locality'
    | '/rent/$city/$locality'
    | '/admin/'
    | '/dashboard/'
    | '/buy/$city/'
    | '/commercial/$city/'
    | '/rent/$city/'
    | '/api/public/properties/$id/contact'
    | '/api/public/properties/$id/report'
    | '/api/public/properties/$id/save'
    | '/api/public/properties/$id/schedule-visit'
    | '/api/public/properties/$id/share'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/favorites'
    | '/help'
    | '/notifications'
    | '/plans'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/why-us'
    | '/auth/callback'
    | '/list-property/wizard'
    | '/properties/$id'
    | '/tenant/matches'
    | '/tenant/onboarding'
    | '/buy'
    | '/commercial'
    | '/list-property'
    | '/properties'
    | '/rent'
    | '/admin/access'
    | '/admin/activity'
    | '/admin/analytics'
    | '/admin/moderation'
    | '/admin/users'
    | '/dashboard/admin'
    | '/dashboard/agent'
    | '/dashboard/customer'
    | '/dashboard/owner'
    | '/dashboard/tenant-profile'
    | '/api/auth/login-notification'
    | '/api/public/enquiries'
    | '/buy/$city/$locality'
    | '/commercial/$city/$locality'
    | '/rent/$city/$locality'
    | '/admin'
    | '/dashboard'
    | '/buy/$city'
    | '/commercial/$city'
    | '/rent/$city'
    | '/api/public/properties/$id/contact'
    | '/api/public/properties/$id/report'
    | '/api/public/properties/$id/save'
    | '/api/public/properties/$id/schedule-visit'
    | '/api/public/properties/$id/share'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/agents'
    | '/auth'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/cookie-policy'
    | '/favorites'
    | '/help'
    | '/list-property'
    | '/notifications'
    | '/plans'
    | '/pricing'
    | '/privacy-policy'
    | '/profile'
    | '/properties'
    | '/refund-policy'
    | '/sitemap.xml'
    | '/terms-of-service'
    | '/why-us'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/auth_/callback'
    | '/list-property/wizard'
    | '/properties/$id'
    | '/tenant/matches'
    | '/tenant/onboarding'
    | '/buy/'
    | '/commercial/'
    | '/list-property/'
    | '/properties/'
    | '/rent/'
    | '/_authenticated/admin/access'
    | '/_authenticated/admin/activity'
    | '/_authenticated/admin/analytics'
    | '/_authenticated/admin/moderation'
    | '/_authenticated/admin/users'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/agent'
    | '/_authenticated/dashboard/customer'
    | '/_authenticated/dashboard/owner'
    | '/_authenticated/dashboard/tenant-profile'
    | '/api/auth/login-notification'
    | '/api/public/enquiries'
    | '/buy/$city/$locality'
    | '/commercial/$city/$locality'
    | '/rent/$city/$locality'
    | '/_authenticated/admin/'
    | '/_authenticated/dashboard/'
    | '/buy/$city/'
    | '/commercial/$city/'
    | '/rent/$city/'
    | '/api/public/properties/$id/contact'
    | '/api/public/properties/$id/report'
    | '/api/public/properties/$id/save'
    | '/api/public/properties/$id/schedule-visit'
    | '/api/public/properties/$id/share'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AgentsRoute: typeof AgentsRoute
  AuthRoute: typeof AuthRoute
  BlogRoute: typeof BlogRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiePolicyRoute: typeof CookiePolicyRoute
  FavoritesRoute: typeof FavoritesRoute
  HelpRoute: typeof HelpRoute
  ListPropertyRoute: typeof ListPropertyRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PlansRoute: typeof PlansRoute
  PricingRoute: typeof PricingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProfileRoute: typeof ProfileRoute
  PropertiesRoute: typeof PropertiesRouteWithChildren
  RefundPolicyRoute: typeof RefundPolicyRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsOfServiceRoute: typeof TermsOfServiceRoute
  WhyUsRoute: typeof WhyUsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  TenantMatchesRoute: typeof TenantMatchesRoute
  TenantOnboardingRoute: typeof TenantOnboardingRoute
  BuyIndexRoute: typeof BuyIndexRoute
  CommercialIndexRoute: typeof CommercialIndexRoute
  RentIndexRoute: typeof RentIndexRoute
  ApiAuthLoginNotificationRoute: typeof ApiAuthLoginNotificationRoute
  ApiPublicEnquiriesRoute: typeof ApiPublicEnquiriesRoute
  BuyCityLocalityRoute: typeof BuyCityLocalityRoute
  CommercialCityLocalityRoute: typeof CommercialCityLocalityRoute
  RentCityLocalityRoute: typeof RentCityLocalityRoute
  BuyCityIndexRoute: typeof BuyCityIndexRoute
  CommercialCityIndexRoute: typeof CommercialCityIndexRoute
  RentCityIndexRoute: typeof RentCityIndexRoute
  ApiPublicPropertiesIdContactRoute: typeof ApiPublicPropertiesIdContactRoute
  ApiPublicPropertiesIdReportRoute: typeof ApiPublicPropertiesIdReportRoute
  ApiPublicPropertiesIdSaveRoute: typeof ApiPublicPropertiesIdSaveRoute
  ApiPublicPropertiesIdScheduleVisitRoute: typeof ApiPublicPropertiesIdScheduleVisitRoute
  ApiPublicPropertiesIdShareRoute: typeof ApiPublicPropertiesIdShareRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookie-policy': {
      id: '/cookie-policy'
      path: '/cookie-policy'
      fullPath: '/cookie-policy'
      preLoaderRoute: typeof CookiePolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plans': {
      id: '/plans'
      path: '/plans'
      fullPath: '/plans'
      preLoaderRoute: typeof PlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-policy': {
      id: '/refund-policy'
      path: '/refund-policy'
      fullPath: '/refund-policy'
      preLoaderRoute: typeof RefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-of-service': {
      id: '/terms-of-service'
      path: '/terms-of-service'
      fullPath: '/terms-of-service'
      preLoaderRoute: typeof TermsOfServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-us': {
      id: '/why-us'
      path: '/why-us'
      fullPath: '/why-us'
      preLoaderRoute: typeof WhyUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth_/callback': {
      id: '/auth_/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/': {
      id: '/buy/'
      path: '/buy'
      fullPath: '/buy/'
      preLoaderRoute: typeof BuyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial/': {
      id: '/commercial/'
      path: '/commercial'
      fullPath: '/commercial/'
      preLoaderRoute: typeof CommercialIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property/': {
      id: '/list-property/'
      path: '/'
      fullPath: '/list-property/'
      preLoaderRoute: typeof ListPropertyIndexRouteImport
      parentRoute: typeof ListPropertyRoute
    }
    '/list-property/wizard': {
      id: '/list-property/wizard'
      path: '/wizard'
      fullPath: '/list-property/wizard'
      preLoaderRoute: typeof ListPropertyWizardRouteImport
      parentRoute: typeof ListPropertyRoute
    }
    '/properties/': {
      id: '/properties/'
      path: '/'
      fullPath: '/properties/'
      preLoaderRoute: typeof PropertiesIndexRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/properties/$id': {
      id: '/properties/$id'
      path: '/$id'
      fullPath: '/properties/$id'
      preLoaderRoute: typeof PropertiesIdRouteImport
      parentRoute: typeof PropertiesRoute
    }
    '/rent/': {
      id: '/rent/'
      path: '/rent'
      fullPath: '/rent/'
      preLoaderRoute: typeof RentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/matches': {
      id: '/tenant/matches'
      path: '/tenant/matches'
      fullPath: '/tenant/matches'
      preLoaderRoute: typeof TenantMatchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tenant/onboarding': {
      id: '/tenant/onboarding'
      path: '/tenant/onboarding'
      fullPath: '/tenant/onboarding'
      preLoaderRoute: typeof TenantOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/access': {
      id: '/_authenticated/admin/access'
      path: '/access'
      fullPath: '/admin/access'
      preLoaderRoute: typeof AuthenticatedAdminAccessRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/activity': {
      id: '/_authenticated/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AuthenticatedAdminActivityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/analytics': {
      id: '/_authenticated/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AuthenticatedAdminAnalyticsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/moderation': {
      id: '/_authenticated/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AuthenticatedAdminModerationRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/agent': {
      id: '/_authenticated/dashboard/agent'
      path: '/agent'
      fullPath: '/dashboard/agent'
      preLoaderRoute: typeof AuthenticatedDashboardAgentRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/customer': {
      id: '/_authenticated/dashboard/customer'
      path: '/customer'
      fullPath: '/dashboard/customer'
      preLoaderRoute: typeof AuthenticatedDashboardCustomerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/owner': {
      id: '/_authenticated/dashboard/owner'
      path: '/owner'
      fullPath: '/dashboard/owner'
      preLoaderRoute: typeof AuthenticatedDashboardOwnerRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/tenant-profile': {
      id: '/_authenticated/dashboard/tenant-profile'
      path: '/tenant-profile'
      fullPath: '/dashboard/tenant-profile'
      preLoaderRoute: typeof AuthenticatedDashboardTenantProfileRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/api/auth/login-notification': {
      id: '/api/auth/login-notification'
      path: '/api/auth/login-notification'
      fullPath: '/api/auth/login-notification'
      preLoaderRoute: typeof ApiAuthLoginNotificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/enquiries': {
      id: '/api/public/enquiries'
      path: '/api/public/enquiries'
      fullPath: '/api/public/enquiries'
      preLoaderRoute: typeof ApiPublicEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$city/': {
      id: '/buy/$city/'
      path: '/buy/$city'
      fullPath: '/buy/$city/'
      preLoaderRoute: typeof BuyCityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buy/$city/$locality': {
      id: '/buy/$city/$locality'
      path: '/buy/$city/$locality'
      fullPath: '/buy/$city/$locality'
      preLoaderRoute: typeof BuyCityLocalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial/$city/': {
      id: '/commercial/$city/'
      path: '/commercial/$city'
      fullPath: '/commercial/$city/'
      preLoaderRoute: typeof CommercialCityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/commercial/$city/$locality': {
      id: '/commercial/$city/$locality'
      path: '/commercial/$city/$locality'
      fullPath: '/commercial/$city/$locality'
      preLoaderRoute: typeof CommercialCityLocalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$city/': {
      id: '/rent/$city/'
      path: '/rent/$city'
      fullPath: '/rent/$city/'
      preLoaderRoute: typeof RentCityIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent/$city/$locality': {
      id: '/rent/$city/$locality'
      path: '/rent/$city/$locality'
      fullPath: '/rent/$city/$locality'
      preLoaderRoute: typeof RentCityLocalityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/contact': {
      id: '/api/public/properties/$id/contact'
      path: '/api/public/properties/$id/contact'
      fullPath: '/api/public/properties/$id/contact'
      preLoaderRoute: typeof ApiPublicPropertiesIdContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/report': {
      id: '/api/public/properties/$id/report'
      path: '/api/public/properties/$id/report'
      fullPath: '/api/public/properties/$id/report'
      preLoaderRoute: typeof ApiPublicPropertiesIdReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/save': {
      id: '/api/public/properties/$id/save'
      path: '/api/public/properties/$id/save'
      fullPath: '/api/public/properties/$id/save'
      preLoaderRoute: typeof ApiPublicPropertiesIdSaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/schedule-visit': {
      id: '/api/public/properties/$id/schedule-visit'
      path: '/api/public/properties/$id/schedule-visit'
      fullPath: '/api/public/properties/$id/schedule-visit'
      preLoaderRoute: typeof ApiPublicPropertiesIdScheduleVisitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/properties/$id/share': {
      id: '/api/public/properties/$id/share'
      path: '/api/public/properties/$id/share'
      fullPath: '/api/public/properties/$id/share'
      preLoaderRoute: typeof ApiPublicPropertiesIdShareRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAccessRoute: typeof AuthenticatedAdminAccessRoute
  AuthenticatedAdminActivityRoute: typeof AuthenticatedAdminActivityRoute
  AuthenticatedAdminAnalyticsRoute: typeof AuthenticatedAdminAnalyticsRoute
  AuthenticatedAdminModerationRoute: typeof AuthenticatedAdminModerationRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAccessRoute: AuthenticatedAdminAccessRoute,
    AuthenticatedAdminActivityRoute: AuthenticatedAdminActivityRoute,
    AuthenticatedAdminAnalyticsRoute: AuthenticatedAdminAnalyticsRoute,
    AuthenticatedAdminModerationRoute: AuthenticatedAdminModerationRoute,
    AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
    AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRoute
  AuthenticatedDashboardAgentRoute: typeof AuthenticatedDashboardAgentRoute
  AuthenticatedDashboardCustomerRoute: typeof AuthenticatedDashboardCustomerRoute
  AuthenticatedDashboardOwnerRoute: typeof AuthenticatedDashboardOwnerRoute
  AuthenticatedDashboardTenantProfileRoute: typeof AuthenticatedDashboardTenantProfileRoute
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute: AuthenticatedDashboardAdminRoute,
    AuthenticatedDashboardAgentRoute: AuthenticatedDashboardAgentRoute,
    AuthenticatedDashboardCustomerRoute: AuthenticatedDashboardCustomerRoute,
    AuthenticatedDashboardOwnerRoute: AuthenticatedDashboardOwnerRoute,
    AuthenticatedDashboardTenantProfileRoute:
      AuthenticatedDashboardTenantProfileRoute,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ListPropertyRouteChildren {
  ListPropertyWizardRoute: typeof ListPropertyWizardRoute
  ListPropertyIndexRoute: typeof ListPropertyIndexRoute
}

const ListPropertyRouteChildren: ListPropertyRouteChildren = {
  ListPropertyWizardRoute: ListPropertyWizardRoute,
  ListPropertyIndexRoute: ListPropertyIndexRoute,
}

const ListPropertyRouteWithChildren = ListPropertyRoute._addFileChildren(
  ListPropertyRouteChildren,
)

interface PropertiesRouteChildren {
  PropertiesIdRoute: typeof PropertiesIdRoute
  PropertiesIndexRoute: typeof PropertiesIndexRoute
}

const PropertiesRouteChildren: PropertiesRouteChildren = {
  PropertiesIdRoute: PropertiesIdRoute,
  PropertiesIndexRoute: PropertiesIndexRoute,
}

const PropertiesRouteWithChildren = PropertiesRoute._addFileChildren(
  PropertiesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AgentsRoute: AgentsRoute,
  AuthRoute: AuthRoute,
  BlogRoute: BlogRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiePolicyRoute: CookiePolicyRoute,
  FavoritesRoute: FavoritesRoute,
  HelpRoute: HelpRoute,
  ListPropertyRoute: ListPropertyRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PlansRoute: PlansRoute,
  PricingRoute: PricingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProfileRoute: ProfileRoute,
  PropertiesRoute: PropertiesRouteWithChildren,
  RefundPolicyRoute: RefundPolicyRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsOfServiceRoute: TermsOfServiceRoute,
  WhyUsRoute: WhyUsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  TenantMatchesRoute: TenantMatchesRoute,
  TenantOnboardingRoute: TenantOnboardingRoute,
  BuyIndexRoute: BuyIndexRoute,
  CommercialIndexRoute: CommercialIndexRoute,
  RentIndexRoute: RentIndexRoute,
  ApiAuthLoginNotificationRoute: ApiAuthLoginNotificationRoute,
  ApiPublicEnquiriesRoute: ApiPublicEnquiriesRoute,
  BuyCityLocalityRoute: BuyCityLocalityRoute,
  CommercialCityLocalityRoute: CommercialCityLocalityRoute,
  RentCityLocalityRoute: RentCityLocalityRoute,
  BuyCityIndexRoute: BuyCityIndexRoute,
  CommercialCityIndexRoute: CommercialCityIndexRoute,
  RentCityIndexRoute: RentCityIndexRoute,
  ApiPublicPropertiesIdContactRoute: ApiPublicPropertiesIdContactRoute,
  ApiPublicPropertiesIdReportRoute: ApiPublicPropertiesIdReportRoute,
  ApiPublicPropertiesIdSaveRoute: ApiPublicPropertiesIdSaveRoute,
  ApiPublicPropertiesIdScheduleVisitRoute:
    ApiPublicPropertiesIdScheduleVisitRoute,
  ApiPublicPropertiesIdShareRoute: ApiPublicPropertiesIdShareRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
