// Generated by Lovable, then hand-edited to add the session-liveness check
// documented in `requireSupabaseAuth`. Re-generating this file would silently
// reintroduce that vulnerability, so preserve the check on any regeneration.
import { createMiddleware } from "@tanstack/react-start";
import { getRequest } from "@tanstack/react-start/server";
import { createClient } from "@supabase/supabase-js";
import type { Database } from "./types";
import { checkSessionLive } from "./session-liveness.server";

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith("sb_publishable_") || value.startsWith("sb_secret_");
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== "undefined" && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (
      isNewSupabaseApiKey(supabaseKey) &&
      headers.get("Authorization") === `Bearer ${supabaseKey}`
    ) {
      headers.delete("Authorization");
    }

    headers.set("apikey", supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: "function" }).server(
  async ({ next }) => {
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      const missing = [
        ...(!SUPABASE_URL ? ["SUPABASE_URL"] : []),
        ...(!SUPABASE_PUBLISHABLE_KEY ? ["SUPABASE_PUBLISHABLE_KEY"] : []),
      ];
      const message = `Missing Supabase environment variable(s): ${missing.join(", ")}. Set them in Vercel \u2192 Project \u2192 Settings \u2192 Environment Variables.`;
      console.error(`[Supabase] ${message}`);
      throw new Error(message);
    }

    const request = getRequest();

    if (!request?.headers) {
      throw new Error("Unauthorized: No request headers available");
    }

    const authHeader = request.headers.get("authorization");

    if (!authHeader) {
      throw new Error("Unauthorized: No authorization header provided");
    }

    const match = authHeader.match(/^Bearer\s+([A-Za-z0-9-_=.]+)\s*$/);
    if (!match) {
      throw new Error("Unauthorized: Only Bearer tokens in valid format are supported");
    }

    const token = match[1];
    if (!token) {
      throw new Error("Unauthorized: No token provided");
    }

    if (token.split(".").length !== 3) {
      throw new Error("Unauthorized: Invalid token");
    }

    const supabase = createClient<Database>(SUPABASE_URL!, SUPABASE_PUBLISHABLE_KEY!, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
        headers: {
          Authorization: `Bearer ${token}`,
        },
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      },
    });

    // Step 1 — signature, issuer, audience, and expiry verification.
    // This project signs with ES256, so `getClaims` verifies locally against the JWKS:
    // fast, and it rejects forged, malformed, unsupported algorithms, and expired tokens.
    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error("Unauthorized: Invalid token");
    }

    if (!data.claims.sub || typeof data.claims.sub !== "string") {
      throw new Error("Unauthorized: No user ID found in token");
    }

    // Validate Issuer claim if present
    if (data.claims.iss && typeof data.claims.iss === "string") {
      const normalizedBase = SUPABASE_URL.replace(/\/$/, "");
      if (!data.claims.iss.startsWith(normalizedBase)) {
        throw new Error("Unauthorized: Token issuer mismatch");
      }
    }

    // Validate Audience claim if present
    if (data.claims.aud && typeof data.claims.aud === "string") {
      if (data.claims.aud !== "authenticated") {
        throw new Error("Unauthorized: Invalid token audience");
      }
    }

    // Validate Expiration claim if present
    if (typeof data.claims.exp === "number") {
      const now = Math.floor(Date.now() / 1000);
      if (data.claims.exp <= now) {
        throw new Error("Unauthorized: Token has expired");
      }
    }

    // Step 2 — session liveness. A local signature check alone is NOT enough:
    // an access token stays cryptographically valid for the remainder of its
    // hour-long TTL after the user signs out, so step 1 on its own would keep
    // authorizing a logged-out session. See `session-liveness.server`.
    const liveness = await checkSessionLive(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, token);
    if (!liveness.live) {
      throw new Error("Unauthorized: Session is no longer valid");
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
