import { describe, it, expect } from "vitest";
import fs from "node:fs";
import path from "node:path";
import {
  normalizeEmail as clientNormalize,
  safeNextPath,
} from "@/modules/authentication/services/emailOtp";
import { normalizeEmail as serverNormalize } from "@/routes/api/auth/request-otp";

const read = (p: string) => fs.readFileSync(path.join(process.cwd(), p), "utf8");
const strip = (s: string) =>
  s
    .replace(/\/\*[\s\S]*?\*\//g, "")
    .replace(/^\s*\/\/.*$/gm, "")
    .replace(/\{\/\*[\s\S]*?\*\/\}/g, "");

const REQUEST_SRC = read("src/routes/api/auth/request-otp.ts");
const OTP_SVC_SRC = read("src/modules/authentication/services/emailOtp.ts");
const FORM_SRC = read("src/modules/authentication/components/EmailOtpForm.tsx");
const AUTH_SRC = read("src/routes/auth.tsx");

describe("A. email normalization", () => {
  it("2. trims and lowercases consistently on client and server", () => {
    for (const norm of [clientNormalize, serverNormalize]) {
      expect(norm("  A@X.CoM ")).toBe("a@x.com");
      expect(norm("User@Domain.COM")).toBe("user@domain.com");
    }
  });
  it("server normalization is defensive against non-strings", () => {
    expect(serverNormalize(undefined)).toBe("");
    expect(serverNormalize(42)).toBe("");
  });
});

describe("B/G. OTP request endpoint — limits, enumeration, no manual OTP", () => {
  it("1. has Supabase generate the code (admin.generateLink), never a hand-rolled one", () => {
    const s = strip(REQUEST_SRC);
    // The code is generated by Supabase (generateLink) and delivered by us via
    // Resend; no Math.random / crypto OTP is ever rolled by hand.
    expect(s).toMatch(/generateLink/);
    expect(s).not.toMatch(/Math\.random|generateOtp|crypto\.randomInt.*otp/i);
  });
  it("4+5. enforces BOTH per-IP and per-email limits", () => {
    const s = strip(REQUEST_SRC);
    expect(s).toMatch(/otp:ip:hourly/);
    expect(s).toMatch(/otp:email:hourly/);
    expect(s).toMatch(/checkRateLimits/);
  });
  it("12. is enumeration-safe: the success response never branches on account existence", () => {
    const s = strip(REQUEST_SRC);
    // Always resolves ok:true on a well-formed request.
    expect(s).toMatch(/ok:\s*true/);
    // A first-time email is provisioned (pre-confirmed) rather than rejected, so
    // exists-vs-not can't change the outcome.
    expect(s).toMatch(/email_confirm:\s*true/);
  });
  it("2. rejects a malformed email before consuming a limiter slot", () => {
    const s = strip(REQUEST_SRC);
    const emailCheck = s.indexOf("EMAIL_RE.test");
    const limiter = s.indexOf("checkRateLimits(");
    expect(emailCheck).toBeGreaterThan(-1);
    expect(emailCheck, "format check must precede the limiter").toBeLessThan(limiter);
  });
  it("never logs the OTP value", () => {
    const s = strip(REQUEST_SRC);
    // Audit details record only the `delivered` boolean and rule name — never a token.
    expect(s).not.toMatch(/token:\s*(otp|code|token)/i);
    expect(s).toMatch(/\bdelivered\b/);
  });
  it("13+14. request redirect is constrained to internal paths", () => {
    const s = strip(REQUEST_SRC);
    expect(s).toMatch(/safeNext/);
  });
});

describe("safeNextPath — open-redirect rejection (client mirror)", () => {
  it("13. preserves a legitimate internal destination", () => {
    expect(safeNextPath("/properties?listing=rent")).toBe("/properties?listing=rent");
    expect(safeNextPath("/property/abc-123")).toBe("/property/abc-123");
  });
  it("14. rejects external and protocol-relative URLs", () => {
    expect(safeNextPath("https://attacker.example")).toBe("/");
    expect(safeNextPath("//attacker.example")).toBe("/");
    expect(safeNextPath("http://evil.com/path")).toBe("/");
  });
  it("rejects a loop back into /auth and empty/nullish input", () => {
    expect(safeNextPath("/auth")).toBe("/");
    expect(safeNextPath("/auth/callback")).toBe("/");
    expect(safeNextPath(null)).toBe("/");
    expect(safeNextPath("")).toBe("/");
  });
});

describe("C. verify uses Supabase Auth, type email, guards input", () => {
  it("4+6+7+8. verifies through Supabase verifyOtp with type 'email'", () => {
    const s = strip(OTP_SVC_SRC);
    expect(s).toMatch(/verifyOtp/);
    expect(s).toMatch(/type:\s*["']email["']/);
  });
  it("5. rejects a code outside the accepted digit range before hitting the network", () => {
    const s = strip(OTP_SVC_SRC);
    expect(s).toMatch(/\{6,8\}/);
  });
  it("6+7. distinguishes expired from invalid without echoing the code", () => {
    const s = strip(OTP_SVC_SRC);
    expect(s).toMatch(/expired/i);
    expect(s).toMatch(/incorrect|invalid/i);
    expect(s).not.toMatch(/console\.(log|info|warn).*code/i);
  });
});

describe("E. provisioning stays customer-only (unchanged by this feature)", () => {
  it("10+11. OTP form never sends a role and defaults display to customer", () => {
    const s = strip(FORM_SRC);
    expect(s).toMatch(/role:\s*["']customer["']/);
    // The form must not offer or transmit any privileged role.
    expect(s).not.toMatch(/admin|employee|dealer|agent/i);
  });
  it("the DB trigger that hardcodes customer is present and untouched", () => {
    const mig = read(
      "supabase/migrations/20260817000000_restrict_self_registration_to_customer.sql",
    );
    expect(mig).toMatch(/VALUES \(NEW\.id, 'customer'::public\.app_role\)/);
  });
});

describe("F+18. added alongside existing methods, redirect preserved", () => {
  it("18. password and Google auth remain wired in auth.tsx", () => {
    expect(AUTH_SRC).toMatch(/EnterprisePasswordForm/);
    expect(AUTH_SRC).toMatch(/GoogleSignInButton/);
  });
  it("OTP is added, not substituted", () => {
    expect(AUTH_SRC).toMatch(/EmailOtpForm/);
    // Both branches of the method switch exist.
    expect(AUTH_SRC).toMatch(/method === "password"/);
  });
  it("13. the original redirect flows into the OTP form and its success handler", () => {
    expect(AUTH_SRC).toMatch(/EmailOtpForm[\s\S]{0,80}redirect=\{redirect\}/);
    expect(AUTH_SRC).toMatch(/safeRedirect\(redirect\)/);
  });
});

describe("D+17. session + secret safety", () => {
  it("17. no service_role or Resend secret is referenced in client-reachable OTP code", () => {
    for (const src of [OTP_SVC_SRC, FORM_SRC]) {
      expect(src).not.toMatch(/SERVICE_ROLE|RESEND_API_KEY|service_role/);
    }
  });
  it("request endpoint reaches Supabase only via server modules", () => {
    const s = strip(REQUEST_SRC);
    // Server-only imports are dynamic and server-scoped; no VITE_-prefixed secret.
    expect(s).not.toMatch(/VITE_[A-Z_]*SERVICE|VITE_[A-Z_]*RESEND/);
  });
});
